### ISSUE TITLE
documentation

### ISSUE THREAD

**Issue by mbande** [jasonbelmonti/mmdl#1]
any docs here?

**Comment by jasonbelmonti** [comment]
Not yet - I can definitely write some if you are interested.  However, I am at a critical point trying to abstract and simplify application bootstrapping that will change the library significantly.  Thanks for your interest!

**Comment by jasonbelmonti** [comment]
Rudimentary documentation is included in release 0.0.20

**Comment by mbande** [comment]
Thanks @jasonbelmonti
